project_id = "qiikjhvzlwzysbtzhdcd"

[functions.create-checkout]
verify_jwt = false

[functions.verify-checkout-session]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.update-super-admin-email]
verify_jwt = false
