project_id = "qiikjhvzlwzysbtzhdcd"

[functions.create-checkout]
verify_jwt = false

[functions.verify-checkout-session]
verify_jwt = false

[functions.complete-paid-signup]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.update-super-admin-email]
verify_jwt = false

[functions.generate-tasks]
verify_jwt = false

[functions.create-virtual-assistant]
verify_jwt = false

[functions.update-virtual-assistant]
verify_jwt = false

[functions.update-va-pricing]
verify_jwt = false

[functions.complete-specialist-registration]
verify_jwt = false

[functions.get-organization-users]
verify_jwt = false

[functions.send-invite]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.get-invoices]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
