project_id = "qiikjhvzlwzysbtzhdcd"

[functions.create-checkout]
verify_jwt = false

[functions.verify-checkout-session]
verify_jwt = false

[functions.complete-paid-signup]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.update-super-admin-email]
verify_jwt = false

[functions.confirm-invited-user]
verify_jwt = false

[functions.generate-tasks]
verify_jwt = false

[functions.create-virtual-assistant]
verify_jwt = false

[functions.update-virtual-assistant]
verify_jwt = false

[functions.update-va-pricing]
verify_jwt = false

[functions.complete-specialist-registration]
verify_jwt = false

[functions.get-organization-users]
verify_jwt = false

[functions.send-invite]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.get-invoices]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.create-storage-checkout]
verify_jwt = false

[functions.verify-storage-purchase]
verify_jwt = false

[functions.create-dataroom-storage-checkout]
verify_jwt = false

[functions.verify-dataroom-storage-purchase]
verify_jwt = false

[functions.create-invited-user]
verify_jwt = false

[functions.remove-team-member-by-email]
verify_jwt = false

[functions.get-member-emails]
verify_jwt = false

[functions.create-va-checkout]
verify_jwt = false

[functions.get-va-subscriptions]
verify_jwt = false

[functions.cancel-va-subscription]
verify_jwt = false

[functions.send-data-room-invite]
verify_jwt = false

[functions.get-nda-details]
verify_jwt = false

[functions.sign-nda]
verify_jwt = false

[functions.accept-data-room-invite]
verify_jwt = false

[functions.get-guest-data-room-content]
verify_jwt = false
